# Generated by Django 3.0.7 on 2020-08-12 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_auto_20200812_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageflag',
            old_name='flag',
            new_name='flag_type',
        ),
        migrations.RemoveField(
            model_name='messageflag',
            name='message',
        ),
        migrations.AddField(
            model_name='messageflag',
            name='content',
            field=models.TextField(default=''),
        ),
    ]
