# Generated by Django 3.0.7 on 2020-08-12 20:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20200812_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageflag',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='messageflag',
            name='content',
            field=models.TextField(),
        ),
    ]
