# Generated by Django 3.0.7 on 2020-08-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20200812_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messageflag',
            old_name='timestamp',
            new_name='created',
        ),
    ]
