version: "3"

services:
  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_PASSWORD='Y1pP;C}uTK}wcly|s4MY[>3WDr:&VM'
    ports:
      - "5432:5432"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
  backend:
    build:
      context: ./backend
    command: gunicorn PeerSupport.wsgi --bind 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - redis
  frontend:
    build:
      context: ./frontend
    volumes:
      - build_folder:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - 80:8080
    volumes:
      - ./webserver/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - build_folder:/var/www/frontend
    depends_on:
      - backend
      - frontend
volumes:
  build_folder:
