# Generated by Django 3.0.5 on 2020-04-24 21:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of Event', max_length=200, verbose_name='Name of Event')),
                ('start_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Starting Time', verbose_name='Starting Time')),
                ('end_time', models.DateTimeField(default=django.utils.timezone.now, help_text='Ending Time', verbose_name='Ending Time')),
                ('description', models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(blank=True, related_name='Users', to='Profile.Profile')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Manage Events',
            },
        ),
    ]
