# Generated by Django 3.0.4 on 2020-04-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='users',
        ),
    ]
