# Generated by Django 3.0.4 on 2020-04-14 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200414_1601'),
        ('events', '0002_remove_event_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='Users', to='Profile.Profile'),
        ),
    ]
