# Generated by Django 3.0.3 on 2020-03-03 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_auto_20200303_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, help_text='Description', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='Name of Event', max_length=200, verbose_name='Name of Event'),
        ),
    ]
