# Generated by Django 3.0.3 on 2020-03-05 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('events', '0008_auto_20200304_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chats', to='chat.Chat'),
        ),
    ]
