# Generated by Django 3.0.3 on 2020-03-05 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('events', '0009_event_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chats',
        ),
        migrations.AddField(
            model_name='event',
            name='chats',
            field=models.ManyToManyField(blank=True, related_name='chats', to='chat.Chat'),
        ),
    ]
