# Generated by Django 3.0.3 on 2020-03-05 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200304_2156'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chats',
        ),
    ]
