# Generated by Django 3.0.4 on 2020-03-31 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_remove_chat_event'),
        ('events', '0011_remove_event_chats'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='chats',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='chat.Chat'),
        ),
    ]
