# Generated by Django 3.0.4 on 2020-03-31 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_event_chats'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='chats',
        ),
    ]
