# Generated by Django 3.0.4 on 2020-04-03 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_eventmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventManager',
        ),
    ]
