# Generated by Django 3.0.3 on 2020-04-10 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0008_profile_best_matches'),
        ('events', '0015_delete_eventmanager'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='users', to='Profile.Profile'),
        ),
    ]
