# Generated by Django 3.0.7 on 2020-07-24 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('message', '0001_initial'),
        ('events', '0001_initial'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.Event')),
                ('messages', models.ManyToManyField(blank=True, to='message.Message')),
                ('participants', models.ManyToManyField(blank=True, related_name='participants', to='Profile.Profile')),
            ],
        ),
    ]
