# Generated by Django 3.0.7 on 2020-06-23 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageFlag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag', models.CharField(choices=[('Suicidal', 'Suicidal Ideation'), ('Violent', 'Potential Violence'), ('Harassment', 'Harassment')], max_length=32)),
                ('message', models.ManyToManyField(to='chat.Message')),
            ],
        ),
    ]
