# Generated by Django 3.0.7 on 2020-06-23 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_messageflag'),
    ]

    operations = [
        migrations.AddField(
            model_name='messageflag',
            name='chat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chat', to='chat.Chat'),
            preserve_default=False,
        ),
    ]
