# Generated by Django 3.0.7 on 2020-06-23 23:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_messageflag_chat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageflag',
            name='message',
        ),
        migrations.AddField(
            model_name='messageflag',
            name='message',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='message', to='chat.Message'),
            preserve_default=False,
        ),
    ]
