# Generated by Django 3.0.7 on 2020-06-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200623_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messageflag',
            name='message',
        ),
        migrations.AddField(
            model_name='messageflag',
            name='message',
            field=models.ManyToManyField(related_name='message', to='chat.Message'),
        ),
    ]
