<<<<<<< HEAD
# Generated by Django 3.0.4 on 2020-04-14 23:01
=======
# Generated by Django 3.0.5 on 2020-04-15 03:14
>>>>>>> 4120fbed3aa3bbdd72cb00a73585adb9e8012152

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(blank=True, max_length=20, null=True)),
                ('best_matches', models.ManyToManyField(blank=True, related_name='matches', to='Profile.Profile')),
            ],
        ),
    ]
