<<<<<<< HEAD:backend/src/Profile/migrations/0002_auto_20200414_1601.py
# Generated by Django 3.0.4 on 2020-04-14 23:01
=======
# Generated by Django 3.0.5 on 2020-04-15 03:14
>>>>>>> 4120fbed3aa3bbdd72cb00a73585adb9e8012152:backend/src/Profile/migrations/0002_auto_20200414_2314.py

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Profile', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='chat_rooms',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to='chat.Chat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
