# Generated by Django 3.0.2 on 2020-02-14 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200201_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
                ('a3', models.FloatField()),
                ('a4', models.FloatField()),
                ('a5', models.FloatField()),
                ('a6', models.FloatField()),
                ('a7', models.FloatField()),
                ('a8', models.FloatField()),
                ('a9', models.FloatField()),
                ('a10', models.FloatField()),
                ('created', models.DateTimeField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='CounselorQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
                ('a3', models.FloatField()),
                ('a4', models.FloatField()),
                ('a5', models.FloatField()),
                ('a6', models.FloatField()),
                ('a7', models.FloatField()),
                ('a8', models.FloatField()),
                ('a9', models.FloatField()),
                ('a10', models.FloatField()),
                ('created', models.DateTimeField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
    ]
