# Generated by Django 3.0.2 on 2020-02-25 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('Profile', '0002_auto_20200225_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='chat_rooms',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chatsaas', to='chat.Chat'),
        ),
    ]
