# Generated by Django 3.0.5 on 2020-04-17 21:47

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0002_auto_20200414_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('happiness', models.IntegerField()),
                ('hometown', models.IntegerField()),
                ('receiving_giving', models.IntegerField()),
                ('religion', models.IntegerField()),
                ('relation_to_others', models.IntegerField()),
                ('government_assistance', models.IntegerField()),
                ('local_community', models.IntegerField()),
                ('immediate_family', models.IntegerField()),
                ('fulfilling_work', models.IntegerField()),
                ('leader_social_circle', models.IntegerField()),
                ('created', models.DateTimeField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
            options={
                'verbose_name': 'User Quiz',
                'verbose_name_plural': 'User Quizzes',
            },
        ),
        migrations.CreateModel(
            name='ResearchQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('methods', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('specializations', models.CharField(max_length=100)),
                ('goTo', models.CharField(max_length=100)),
                ('understands', models.CharField(max_length=100)),
                ('anon', models.CharField(max_length=100)),
                ('compatible', models.CharField(max_length=100)),
                ('sameProbs', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
            options={
                'verbose_name': 'Research Quiz',
                'verbose_name_plural': 'Research Quizzes',
            },
        ),
        migrations.CreateModel(
            name='CounselorQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a1', models.FloatField()),
                ('a2', models.FloatField()),
                ('a3', models.FloatField()),
                ('a4', models.FloatField()),
                ('a5', models.FloatField()),
                ('a6', models.FloatField()),
                ('a7', models.FloatField()),
                ('a8', models.FloatField()),
                ('a9', models.FloatField()),
                ('a10', models.FloatField()),
                ('created', models.DateTimeField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
            options={
                'verbose_name': 'Counselor Quiz',
                'verbose_name_plural': 'Counselor Quizzes',
            },
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(max_length=255)),
                ('created', models.DateTimeField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non Binary', 'Non Binary'), ('Transgender', 'Transgender'), ('Gender Fluid', 'Gender Fluid'), ('Prefer not to answer', 'Prefer not to answer')], max_length=30, null=True)),
                ('ethnic_origin', multiselectfield.db.fields.MultiSelectField(choices=[('White', 'White'), ('Black or Afican American', 'Black or Afican American'), ('Native American or American Indian', 'Native American or American Indian'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Asian / Pacific Islander', 'Asian / Pacific Islander'), ('Midddle Eastern', 'Middle Eastern'), ('South Asian', 'South Asian'), ('Other', 'Other')], max_length=143)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
    ]
