# Generated by Django 3.0.3 on 2020-02-28 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_counselorquiz_userquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(max_length=100)),
                ('race', models.CharField(max_length=100)),
                ('exp', models.CharField(max_length=100)),
                ('methods', models.CharField(max_length=100)),
                ('age', models.CharField(max_length=100)),
                ('specializations', models.CharField(max_length=100)),
                ('goTo', models.CharField(max_length=100)),
                ('understands', models.CharField(max_length=100)),
                ('anon', models.CharField(max_length=100)),
                ('compatible', models.CharField(max_length=100)),
                ('sameProbs', models.CharField(max_length=100)),
                ('support', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
        ),
    ]
