# Generated by Django 3.0.2 on 2020-02-25 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
        ('Profile', '0003_auto_20200225_1243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='chat_rooms',
        ),
        migrations.AddField(
            model_name='profile',
            name='chat_rooms',
            field=models.ManyToManyField(blank=True, related_name='chat_rooms', to='chat.Chat'),
        ),
    ]
