# Generated by Django 3.0.3 on 2020-03-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_researchquiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselorquiz',
            options={'verbose_name': 'Counselor Quiz', 'verbose_name_plural': 'Counselor Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='researchquiz',
            options={'verbose_name': 'Research Quiz', 'verbose_name_plural': 'Research Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='userquiz',
            options={'verbose_name': 'User Quiz', 'verbose_name_plural': 'User Quizzes'},
        ),
    ]
