# Generated by Django 3.0.3 on 2020-03-03 22:05

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_researchquiz'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=120)),
                ('email', models.EmailField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female'), ('Non Binary', 'Non Binary'), ('Transgender', 'Transgender'), ('Gender Fluid', 'Gender Fluid'), ('Prefer not to answer', 'Prefer not to answer')], max_length=30, null=True)),
                ('ethnic_origin', multiselectfield.db.fields.MultiSelectField(choices=[('White', 'White'), ('Black or Afican American', 'Black or Afican American'), ('Native American or American Indian', 'Native American or American Indian'), ('Hispanic or Latino', 'Hispanic or Latino'), ('Asian / Pacific Islander', 'Asian / Pacific Islander'), ('Midddle Eastern', 'Middle Eastern'), ('South Asian', 'South Asian'), ('Other', 'Other')], max_length=143)),
            ],
        ),
    ]
