# Generated by Django 3.0.3 on 2020-03-05 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_counselor'),
        ('Profile', '0005_auto_20200303_1634'),
    ]

    operations = [
    ]
