# Generated by Django 3.0.2 on 2020-03-05 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20200305_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='friends',
            field=models.ManyToManyField(blank=True, to='Profile.Profile'),
        ),
    ]
