# Generated by Django 3.0.2 on 2020-03-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20200305_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='best_matches',
            field=models.ManyToManyField(blank=True, related_name='matches', to='Profile.Profile'),
        ),
    ]
