# Generated by Django 3.0.2 on 2020-04-14 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room_name',
        ),
        migrations.AddField(
            model_name='message',
            name='p_suicidal',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='p_toxic',
            field=models.FloatField(null=True),
        ),
    ]
