# Generated by Django 3.0.2 on 2020-02-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20200225_1334'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ManyToManyField(related_name='profile', to='Profile.Profile'),
        ),
    ]
