# Generated by Django 3.0.4 on 2020-04-14 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_chat_room_name'),
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.Event'),
        ),
    ]
