# Generated by Django 3.0.2 on 2020-02-25 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20200225_1334'),
        ('chat', '0002_auto_20200225_1334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.AddField(
            model_name='message',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='Profile.Profile'),
        ),
    ]
