# Generated by Django 3.0.2 on 2020-04-14 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200414_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='p_toxic',
            field=models.FloatField(default=0.8, null=True),
        ),
    ]
