# Generated by Django 3.0.2 on 2020-03-05 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0007_auto_20200305_1529'),
        ('chat', '0003_auto_20200225_1336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='profile',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='Profile.Profile'),
        ),
    ]
