# Generated by Django 3.0.2 on 2020-02-20 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0004_auto_20200220_1634'),
        ('chat', '0003_auto_20200220_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='Profile.Profile'),
        ),
    ]
