# Generated by Django 3.0.2 on 2020-04-21 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20200414_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='p_toxic',
            field=models.FloatField(null=True),
        ),
    ]
