# Generated by Django 3.0.2 on 2020-02-20 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200220_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Contact'),
        ),
    ]
