# Generated by Django 3.0.4 on 2020-03-24 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_auto_20200305_1529'),
        ('chat', '0002_chat_event'),
    ]

    operations = [
    ]
