# Generated by Django 3.0.4 on 2020-03-30 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_merge_20200324_1508'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room_name',
        ),
    ]
