# Generated by Django 3.0.2 on 2020-02-20 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_message_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat.Contact'),
        ),
    ]
