# Generated by Django 3.0.4 on 2020-03-30 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_remove_chat_room_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
