# Generated by Django 3.0.4 on 2020-03-30 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_chat_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='event',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='messages',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='participants',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='room_name',
        ),
    ]
