# Generated by Django 3.0.4 on 2020-03-30 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_remove_event_chats'),
        ('Profile', '0008_profile_best_matches'),
        ('chat', '0008_auto_20200329_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event', to='events.Event'),
        ),
        migrations.AddField(
            model_name='chat',
            name='messages',
            field=models.ManyToManyField(blank=True, to='chat.Message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='participants', to='Profile.Profile'),
        ),
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
