# Generated by Django 3.0.4 on 2020-03-30 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_auto_20200329_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='message',
            name='timestamp',
        ),
    ]
