# Generated by Django 3.0.4 on 2020-03-30 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_auto_20200329_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room_name',
        ),
    ]
