# Generated by Django 3.0.4 on 2020-04-13 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0014_chat_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='room_name',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
    ]
