# Generated by Django 3.0.4 on 2020-04-13 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_chat_room_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='room_name',
        ),
    ]
