# Generated by Django 3.0.7 on 2020-07-11 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0003_prestudyquiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q1',
            field=models.IntegerField(default=3, null=True),
        ),
    ]
