# Generated by Django 3.0.7 on 2020-07-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0005_auto_20200711_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q1',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q10',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q11',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q12',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q13',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q14',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q15',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q16',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q17',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q18',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q19',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q2',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q20',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q21',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q3',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q4',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q5',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q6',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q7',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q8',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='prestudyquiz',
            name='q9',
            field=models.IntegerField(default=3),
        ),
    ]
