# Generated by Django 3.0.7 on 2020-07-12 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Profile', '0006_auto_20200711_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeekPostStudyQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(default=3)),
                ('q2', models.IntegerField(default=3)),
                ('q3', models.IntegerField(default=3)),
                ('q4', models.IntegerField(default=3)),
                ('q5', models.IntegerField(default=3)),
                ('q6', models.IntegerField(default=3)),
                ('q7', models.IntegerField(default=3)),
                ('q8', models.IntegerField(default=3)),
                ('q9', models.IntegerField(default=3)),
                ('q10', models.IntegerField(default=3)),
                ('q11', models.IntegerField(default=3)),
                ('q12', models.IntegerField(default=3)),
                ('q13', models.IntegerField(default=3)),
                ('q14', models.IntegerField(default=3)),
                ('q15', models.IntegerField(default=3)),
                ('q16', models.IntegerField(default=3)),
                ('q17', models.IntegerField(default=3)),
                ('q18', models.IntegerField(default=3)),
                ('q19', models.IntegerField(default=3)),
                ('q20', models.IntegerField(default=3)),
                ('q21', models.IntegerField(default=3)),
                ('created', models.DateTimeField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
            options={
                'verbose_name': 'WeekPostStudy Quiz',
                'verbose_name_plural': 'WeekPostStudy Quizzes',
            },
        ),
        migrations.CreateModel(
            name='PostStudyQuiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q1', models.IntegerField(default=3)),
                ('q2', models.IntegerField(default=3)),
                ('q3', models.IntegerField(default=3)),
                ('q4', models.IntegerField(default=3)),
                ('q5', models.IntegerField(default=3)),
                ('q6', models.IntegerField(default=3)),
                ('q7', models.IntegerField(default=3)),
                ('q8', models.IntegerField(default=3)),
                ('q9', models.IntegerField(default=3)),
                ('q10', models.IntegerField(default=3)),
                ('q11', models.IntegerField(default=3)),
                ('q12', models.IntegerField(default=3)),
                ('q13', models.IntegerField(default=3)),
                ('q14', models.IntegerField(default=3)),
                ('q15', models.IntegerField(default=3)),
                ('q16', models.IntegerField(default=3)),
                ('q17', models.IntegerField(default=3)),
                ('q18', models.IntegerField(default=3)),
                ('q19', models.IntegerField(default=3)),
                ('q20', models.IntegerField(default=3)),
                ('created', models.DateTimeField(null=True)),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Profile.Profile')),
            ],
            options={
                'verbose_name': 'PostStudy Quiz',
                'verbose_name_plural': 'PostStudy Quizzes',
            },
        ),
    ]
